
//handles returning a generic response from the server
//takes a express response object to export the response
//takes an error generated by a database call
//takes a content returned by the database
//Takes an optional parameeter key for the key mapping of the reponse key
//takes a message to display if content is null
exports.generic = (res, err, content, key = "content", nullMessage = "Not Found") => {
  if(err){
    //onError sends back the and error message
    return res.status(404).json({error: true, content: err})
  }
  else if(content == null){
    //returns an error if content is null
    return res.status(404).json({error: true, content: nullMessage})
  }
  return res.json({error: false, [key]: content}); //If successful sends back the song with the error false flag
}